# Generated by Django 4.0.4 on 2022-06-06 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='econtact',
            field=models.IntegerField(),
        ),
        migrations.AlterModelTable(
            name='employee',
            table='employee',
        ),
    ]
